# Generated by Django 3.2.5 on 2021-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_comment_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='seiyu',
            name='year_of_birth',
            field=models.DateField(auto_now=True, verbose_name='Year of birth'),
        ),
        migrations.AddField(
            model_name='seiyu',
            name='year_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Year of death'),
        ),
    ]
