# Generated by Django 3.2.5 on 2021-07-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_auto_20210716_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Text'),
        ),
    ]
