# Generated by Django 3.2.5 on 2021-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to='profiles/', verbose_name='Picture'),
        ),
    ]
