# Generated by Django 3.2.5 on 2021-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0008_anime_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='anime',
        ),
        migrations.AddField(
            model_name='character',
            name='animes',
            field=models.ManyToManyField(to='animes.Anime'),
        ),
    ]
