# Generated by Django 3.2.5 on 2021-07-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0011_animescreenshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='Name')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.status'),
        ),
    ]
