# Generated by Django 3.2.5 on 2021-07-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0012_auto_20210718_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Name'),
        ),
    ]
