# Generated by Django 3.2.5 on 2021-07-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0013_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(blank=True, choices=[('anons', 'Announced'), ('air', 'Airing'), ('fin', 'Finished')], max_length=5, null=True, verbose_name='Status'),
        ),
    ]
