# Generated by Django 3.2.5 on 2021-07-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0017_auto_20210719_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='main_character',
            field=models.BooleanField(default=False, verbose_name='Main character'),
        ),
    ]
