# Generated by Django 3.2.5 on 2021-07-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0018_character_main_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animescreenshots',
            options={'verbose_name': 'Anime screenshot', 'verbose_name_plural': 'Anime screenshots'},
        ),
        migrations.AlterModelOptions(
            name='seiyu',
            options={'verbose_name_plural': 'Seiyu'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animes.profile'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(related_name='animes', to='animes.Character'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='animes.Genre'),
        ),
    ]
