# Generated by Django 3.2.5 on 2021-07-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0020_auto_20210721_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(related_name='related_animes', to='animes.Character'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.CreateModel(
            name='AnimeListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Watching', 'Watching'), ('Completed', 'Completed'), ('On hold', 'On hold'), ('Dropped', 'Dropped')], default='Planned', max_length=10, verbose_name='Status')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='animes.animelist')),
            ],
        ),
        migrations.AddField(
            model_name='animelist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anime_list', to='animes.profile'),
        ),
    ]
