# Generated by Django 3.2.5 on 2021-07-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0021_auto_20210723_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='profile',
        ),
        migrations.AddField(
            model_name='rating',
            name='anime_list_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='animes.animelistitem'),
        ),
    ]
