# Generated by Django 3.2.5 on 2021-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0022_auto_20210723_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelistitem',
            name='score',
            field=models.IntegerField(choices=[(0, 'Do not match'), (1, 'Worst'), (2, 'Terrible'), (3, 'Shitty'), (4, 'Bad'), (5, 'So-so'), (6, 'Fine'), (7, 'Good'), (8, 'Excellent'), (9, 'Masterpiece'), (10, 'God tier')], default=0, verbose_name='Score'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
